export enum ConfigEnum {
  PORT = 'PORT',
  CLOUDINARY_NAME = 'CLOUDINARY_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
  CLOUDINARY_PRESET = 'CLOUDINARY_PRESET',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRE_TIME = 'JWT_EXPIRE_TIME',
  MONGO_URI = 'MONGO_URI',
}
